name: Demo Workflow
on: [push] 

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git-actions
        run: |
          git clone https://github.com/Yaswanthkumar1100/Summer-School_Ses_4.git
          cd Summer-School_Ses_4
